spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/app20220916_2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
